### ISSUE TITLE
rocademption

### ISSUE THREAD

**Issue by xrtw** [Puntherline/pun_whitelist#1]
if you stay in a queue, it says Please wait and you cant enter password.
using rocademption

**Comment by Puntherline** [comment]
I'm extremely sorry for my late response, I wasn't on github for a bit. The bug of it getting stuck at "Please wait..." has most likely been fixed in the most recent update. You can try that new version if you want to, if it still doesnt work I will work on fixing this!

**Comment by Puntherline** [comment]
This has been fixed with the most recent build, did some testing using rocademption and I couldn't find any bugs.
